# Copyright (c) [2024] Fergal Somers
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Not a great idea to install via Helm (should really get the resources and deploy)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitoring-crds-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"    
spec:
  project: platform
  source:
    repoURL: https://github.com/fergalsomers/olm-sample.git
    targetRevision: HEAD
    path: base/prometheus-monitoring/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true        
    syncOptions:
    - ServerSideApply=true  # necessary due to generated annotation lengths.