apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: platform-argocd
  namespace: platform
  labels:
    app: platform
spec:
  config:
   env: 
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: platform

