# Copyright (c) [2024] Fergal Somers
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches: 
- path: ./argocd-cm.yaml                  # app-of-apps sync waves
- path: ./argocd-cmd-params-cm.yaml       # configure TLS false
- patch: |-                               # Annoyingly not all can be done via configs you need to set cmdline arg
    - op: add
      path: /spec/template/spec/containers/0/args/1
      value: --disable-tls
  target:
    version: v1
    kind: Deployment
    name: argocd-repo-server

namespace: argocd
