apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/fergalsomers/olm-sample.git
    targetRevision: HEAD
    path: base
    # directory:  (switched to using kustomize for finer control during dev. )
    #   recurse: true # 
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true     
