---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-installer
  namespace: prometheus-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-installer-cluster-role
rules: [
  {
    "apiGroups": [
      "olm.operatorframework.io"
    ],
    "resources": [
      "clusterextensions/finalizers"
    ],
    "verbs": [
      "update"
    ],
    "resourceNames": [
      "prometheus"
    ]
  },
  {
    "apiGroups": [
      "apiextensions.k8s.io"
    ],
    "resources": [
      "customresourcedefinitions"
    ],
    "verbs": [
      "create",
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      "apiextensions.k8s.io"
    ],
    "resources": [
      "customresourcedefinitions"
    ],
    "verbs": [
      "get",
      "update",
      "patch",
      "delete"
    ],
    "resourceNames": [
      "alertmanagerconfigs.monitoring.coreos.com",
      "alertmanagers.monitoring.coreos.com",
      "podmonitors.monitoring.coreos.com",
      "probes.monitoring.coreos.com",
      "prometheusagents.monitoring.coreos.com",
      "prometheuses.monitoring.coreos.com",
      "prometheusrules.monitoring.coreos.com",
      "scrapeconfigs.monitoring.coreos.com",
      "servicemonitors.monitoring.coreos.com",
      "thanosrulers.monitoring.coreos.com"
    ]
  },
  {
    "apiGroups": [
      "rbac.authorization.k8s.io"
    ],
    "resources": [
      "clusterroles"
    ],
    "verbs": [
      "create",
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      "rbac.authorization.k8s.io"
    ],
    "resources": [
      "clusterroles"
    ],
    "verbs": [
      "get",
      "update",
      "patch",
      "delete"
    ],
    "resourceNames": [
      "prometheusoperator-1731m5m3tg1vdmh8ycl55ig57iogzulf7ns9vnm0td1n",
      "prometheusoperator.-wz4g4r2hhvu84vkvhoc07oocuylw0eww67bfwznwof2"
    ]
  },
  {
    "apiGroups": [
      "monitoring.coreos.com"
    ],
    "resources": [
      "alertmanagers",
      "alertmanagers/finalizers",
      "alertmanagers/status",
      "alertmanagerconfigs",
      "prometheuses",
      "prometheuses/finalizers",
      "prometheuses/status",
      "prometheusagents",
      "prometheusagents/finalizers",
      "prometheusagents/status",
      "thanosrulers",
      "thanosrulers/finalizers",
      "thanosrulers/status",
      "scrapeconfigs",
      "servicemonitors",
      "podmonitors",
      "probes",
      "prometheusrules"
    ],
    "verbs": [
      "*"
    ]
  },
  {
    "apiGroups": [
      "apps"
    ],
    "resources": [
      "statefulsets"
    ],
    "verbs": [
      "*"
    ]
  },
  {
    "apiGroups": [
      ""
    ],
    "resources": [
      "configmaps",
      "secrets"
    ],
    "verbs": [
      "*"
    ]
  },
  {
    "apiGroups": [
      ""
    ],
    "resources": [
      "pods"
    ],
    "verbs": [
      "list",
      "delete"
    ]
  },
  {
    "apiGroups": [
      ""
    ],
    "resources": [
      "services",
      "services/finalizers",
      "endpoints"
    ],
    "verbs": [
      "get",
      "create",
      "update",
      "delete"
    ]
  },
  {
    "apiGroups": [
      ""
    ],
    "resources": [
      "nodes"
    ],
    "verbs": [
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      ""
    ],
    "resources": [
      "namespaces"
    ],
    "verbs": [
      "get",
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      "networking.k8s.io"
    ],
    "resources": [
      "ingresses"
    ],
    "verbs": [
      "get",
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      "rbac.authorization.k8s.io"
    ],
    "resources": [
      "clusterrolebindings"
    ],
    "verbs": [
      "create",
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      "rbac.authorization.k8s.io"
    ],
    "resources": [
      "clusterrolebindings"
    ],
    "verbs": [
      "get",
      "update",
      "patch",
      "delete"
    ],
    "resourceNames": [
      "prometheusoperator-1731m5m3tg1vdmh8ycl55ig57iogzulf7ns9vnm0td1n",
      "prometheusoperator.-wz4g4r2hhvu84vkvhoc07oocuylw0eww67bfwznwof2"
    ]
  }
]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-installer-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-installer-cluster-role
subjects:
  - kind: ServiceAccount
    name: prometheus-installer
    namespace: prometheus-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-installer-installer-role
  namespace: prometheus-system
rules: [
  {
    "apiGroups": [
      "apps"
    ],
    "resources": [
      "deployments"
    ],
    "verbs": [
      "create",
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      "apps"
    ],
    "resources": [
      "deployments"
    ],
    "verbs": [
      "get",
      "update",
      "patch",
      "delete"
    ],
    "resourceNames": [
      "prometheus-operator"
    ]
  },
  {
    "apiGroups": [
      ""
    ],
    "resources": [
      "serviceaccounts"
    ],
    "verbs": [
      "create",
      "list",
      "watch"
    ]
  },
  {
    "apiGroups": [
      ""
    ],
    "resources": [
      "serviceaccounts"
    ],
    "verbs": [
      "get",
      "update",
      "patch",
      "delete"
    ],
    "resourceNames": [
      "prometheus-operator"
    ]
  }
]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-installer-installer-role-binding
  namespace: prometheus-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-installer-installer-role
subjects:
  - kind: ServiceAccount
    name: prometheus-installer
    namespace: prometheus-system
---
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: prometheus
spec:
  source:
    sourceType: Catalog
    catalog:
      packageName: prometheus
      version: 0.70.0
  install:
    namespace: prometheus-system
    serviceAccount:
      name: prometheus-installer
