# Not a great idea to install via Helm (should really get the resources and deploy)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-helm-app
  namespace: argocd
spec:
  project: default
  source:
    chart: gatekeeper
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: 3.17.1
    helm:
      releaseName: gatekeeper
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper-system