# Not a great idea to install via Helm (should really get the resources and deploy)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-helm-app
  namespace: argocd
spec:
  project: default
  source:
    chart: gatekeeper
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: 3.17.1
    helm:
      releaseName: gatekeeper
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper-system
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
    